name: deep_learning
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py38_0
  - altgraph=0.16.1=py_0
  - astunparse=1.6.3=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=openblas
  - blinker=1.4=py38_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.11.8=ha878542_0
  - cachetools=4.1.0=py_1
  - certifi=2020.11.8=py38h578d9bd_0
  - cffi=1.14.0=py38he30daa8_1
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - cryptography=2.9.2=py38h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py_2
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.2=he06d7ca_0
  - gast=0.3.3=py_0
  - glib=2.63.1=h3eb4bd4_1
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.27.2=py38hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=nompi_py38h513d04c_102
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=58.2=hf484d3e_1000
  - idna=2.9=py_1
  - ipython=7.16.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.17.1=py38_0
  - joblib=0.15.1=py_0
  - jpeg=9d=h516909a_0
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.3.1=py38_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py38hbf85e49_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_1
  - libprotobuf=3.12.3=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=he19cac6_1
  - libxslt=1.1.34=hc22bd24_0
  - lxml=4.5.1=py38hbb43d70_0
  - lz4-c=1.9.2=he1b5a44_1
  - macholib=1.14=pyh9f0ad1d_1
  - markdown=3.1.1=py38_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38hef1b27d_0
  - ncurses=6.2=he6710b0_1
  - nibabel=3.1.0=py_0
  - numpy=1.18.5=py38h8854b6b_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=h516909a_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.3=py38h0573a6f_0
  - parso=0.7.0=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.1.2=py38hb39fc2d_0
  - pip=20.1.1=py38_1
  - progress=1.5=py_1
  - prompt-toolkit=3.0.5=py_0
  - protobuf=3.12.3=py38he6710b0_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py38_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pydicom=2.0.0=pyh9f0ad1d_0
  - pygments=2.6.1=py_0
  - pyinstaller=4.1=py38haf3832a_1
  - pyinstaller-hooks-contrib=2020.10=pyhd8ed1ab_0
  - pyjwt=1.7.1=py38_0
  - pyopenssl=19.1.0=py38_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py38h05f1152_4
  - pysocks=1.7.1=py38_0
  - python=3.8.3=hcff3b4d_0
  - python-dateutil=2.8.1=py_0
  - python-pptx=0.6.18=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py38h1e0a361_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py38_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scikit-learn=0.23.2=py38h0573a6f_0
  - scipy=1.4.1=py38h18bccfc_3
  - setuptools=47.3.0=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.31.1=h62c20be_1
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=gpu_py38hb782248_0
  - tensorflow-base=2.2.0=gpu_py38h83e3d50_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - tensorflow-gpu=2.2.0=h0d30ee6_0
  - termcolor=1.1.0=py38_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py38h1e0a361_1
  - traitlets=4.3.3=py38_0
  - urllib3=1.25.8=py38_0
  - wcwidth=0.2.5=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py38_0
  - wrapt=1.12.1=py38h7b6447c_1
  - xlsxwriter=1.2.9=pyh9f0ad1d_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - yaspin==1.2.0
prefix: /neuro/users/ivan.gonzalez/miniconda3/envs/deep_learning



